"""Init HFS database

Revision ID: 278594760d32
Revises: 
Create Date: 2023-08-17 09:48:53.846703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278594760d32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('halalStatus', sa.String(), nullable=False),
    sa.Column('lastContacted', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=128), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('salt')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['serviceID'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('suburb', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['serviceID'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id', 'serviceID')
    )
    op.create_table('service_supplier',
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('supplierID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serviceID'], ['service.id'], ),
    sa.ForeignKeyConstraint(['supplierID'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('serviceID', 'supplierID')
    )
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('halalStatus', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['serviceID'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history')
    op.drop_table('service_supplier')
    op.drop_table('location')
    op.drop_table('contact')
    op.drop_table('user')
    op.drop_table('supplier')
    op.drop_table('service')
    # ### end Alembic commands ###
