"""Fixed fields

Revision ID: 526b328720ab
Revises: b2cc9a2aed54
Create Date: 2023-06-27 23:54:42.191482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526b328720ab'
down_revision = 'b2cc9a2aed54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution', sa.Boolean(), nullable=True))
        batch_op.drop_column('globalDistribution')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    with op.batch_alter_table('charity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('globalDistribution', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('distribution')

    # ### end Alembic commands ###
