"""Fixed fields

Revision ID: 5f4289d81045
Revises: 526b328720ab
Create Date: 2023-06-28 00:06:30.522618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4289d81045'
down_revision = '526b328720ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('contact_charityID_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_unique_constraint('contact_charityID_key', ['charityID'])
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
