"""db init

Revision ID: 842777ba7dc4
Revises: 
Create Date: 2023-12-01 17:01:35.972879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842777ba7dc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halal_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('salt')
    )
    op.create_table('food_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastContacted', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('halalStatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['halalStatus'], ['halal_status.id'], ),
    sa.ForeignKeyConstraint(['type'], ['service_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['serviceID'], ['food_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_service_tag_junction',
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('tagID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serviceID'], ['food_service.id'], ),
    sa.ForeignKeyConstraint(['tagID'], ['service_tag.id'], ),
    sa.PrimaryKeyConstraint('serviceID', 'tagID')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('postCode', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['serviceID'], ['food_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_supplier',
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('supplierID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serviceID'], ['food_service.id'], ),
    sa.ForeignKeyConstraint(['supplierID'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('serviceID', 'supplierID')
    )
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceID', sa.Integer(), nullable=False),
    sa.Column('halalStatus', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['halalStatus'], ['halal_status.id'], ),
    sa.ForeignKeyConstraint(['serviceID'], ['food_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history')
    op.drop_table('service_supplier')
    op.drop_table('location')
    op.drop_table('food_service_tag_junction')
    op.drop_table('contact')
    op.drop_table('food_service')
    op.drop_table('user')
    op.drop_table('supplier')
    op.drop_table('service_type')
    op.drop_table('service_tag')
    op.drop_table('halal_status')
    # ### end Alembic commands ###
