"""Edited Location for Geom

Revision ID: b091aa747fac
Revises: ce407ce1596d
Create Date: 2024-06-14 10:49:57.153511

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b091aa747fac'
down_revision = 'ce407ce1596d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add postgis extension
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
       #  batch_op.create_index('idx_location_geom', ['geom'], unique=False, postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
       #  batch_op.drop_index('idx_location_geom', postgresql_using='gist')
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('geom')

    op.execute('DROP EXTENSION IF NOT EXISTS postgis;')

    # ### end Alembic commands ###
