"""Initial migration

Revision ID: b2cc9a2aed54
Revises: 
Create Date: 2023-06-27 22:53:28.943882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cc9a2aed54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('charity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logoURL', sa.String(), nullable=False),
    sa.Column('storefrontURL', sa.String(), nullable=True),
    sa.Column('adminFees', sa.Boolean(), nullable=True),
    sa.Column('globalDistribution', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('charity_category',
    sa.Column('charityID', sa.Integer(), nullable=False),
    sa.Column('categoryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryID'], ['category.id'], ),
    sa.ForeignKeyConstraint(['charityID'], ['charity.id'], ),
    sa.PrimaryKeyConstraint('charityID', 'categoryID')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charityID', sa.Integer(), nullable=False),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['charityID'], ['charity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charityID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    op.drop_table('charity_category')
    op.drop_table('user')
    op.drop_table('charity')
    op.drop_table('category')
    # ### end Alembic commands ###
