"""Added broadcast table

Revision ID: ce407ce1596d
Revises: cbb916b6985d
Create Date: 2024-06-13 13:14:53.033245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce407ce1596d'
down_revision = 'cbb916b6985d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('startTime', sa.Time(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('endTime', sa.Time(), nullable=False),
    sa.Column('isImportant', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcast')
    # ### end Alembic commands ###
